type Query {
  bids: [Bid!]!
  
  auctions: [Auction!]!
  auction(address: String!): Auction
  
  web3Auction(address: String!): Web3Auction!
  web3User(address: String!, auctionAddress: String!): Web3User!
}

# ------ Auction schema ------
type Auction {
  id: Int!
  owner: String!
  address: String!
  name: String!
  winLength: Int!
  description: String
  contentHash: String
  createdAt: String!
  status: String!
  highBid: Int!
  generation: Int!
  revenue: Int!
  bids: [Bid]!
}

input CreateAuctionInput {
  address: String!
  name: String!
  owner: String!
  winLength: Int!
  description: String!
  contentHash: String!
  status: String
  highBid: Int
  generation: Int
}

# Comment out to bypass Fauna `Import your GraphQL schema' error
# type Mutation {
#   createAuction(input: CreateAuctionInput!): Auction
# }

# ------ Bids ------
type Bid {
  id: Int!
  amount: Int!
  auction: Auction!
  auctionAddress: String!
}


input CreateBidInput {
  amount: Int!
  auctionAddress: String!
}

input UpdateBidInput {
  amount: Int
  auctionAddress: String
}

# ------ Web3 ------
type Web3Auction {
  address: String!
  highBidder: String!
  status: String!
  highBid: Int!
  currentGeneration: Int!
  auctionBalance: Int!
  endTime: String!
  lastBidTime: String!
  # Unfortunately, the Fauna GraphQL API does not support custom scalars.
  # Instead, we will just use a 'String!' type, for simplicity.
  pastAuctions: String!
  revenue: Int!
}

type Web3User {
  address: String!
  auctionAddress: String!
  superTokenBalance: String!
  isSubscribed: Boolean!
}